# https://docs.github.com/en/actions

name: "Integrate"

on:
  pull_request: null
  push:
    branches:
      - "master"

jobs:
  build:
    name: Build docs for ${{ matrix.language }}
    strategy:
      matrix:
        language:
          - "de"
          - "en"
          - "es"
          - "fr"
          - "it"
          - "ja"
          - "pl"
          - "pt_br"
          #          - "ro"
          - "ru"
          - "tr"
          - "uk"
          - "zh"
    uses: Ayesh/doc-base/.github/workflows/reusable.yml@master
    with:
      repo: 'php/doc-${{ matrix.language }}'
      language: ${{ matrix.language }}
